# Configuration file for file paths and other constants

# File paths
YUM_CONF="/etc/yum.conf"
GRUB_CFG="/boot/grub2/grub.cfg"
MOTD="/etc/motd"
ISSUE="/etc/issue"
ISSUE_NET="/etc/issue.net"
CHRONY_CONF="/etc/chrony.conf"
CRONTAB="/etc/crontab"
CRON_HOURLY="/etc/cron.hourly"
CRON_DAILY="/etc/cron.daily"
CRON_WEEKLY="/etc/cron.weekly"
CRON_MONTHLY="/etc/cron.monthly"
CRON_DIR="/etc/cron.d"
CRON_ALLOW="/etc/cron.allow"
CRON_DENY="/etc/cron.deny"
AT_ALLOW="/etc/at.allow"
AT_DENY="/etc/at.deny"
SSHD_CFG="/etc/ssh/sshd_config"
SYSTEM_AUTH="/etc/pam.d/system-auth"
PWQUAL_CNF="/etc/security/pwquality.conf"
PAM_SU="/etc/pam.d/su"
LOGIN_DEFS="/etc/login.defs"
PROFILE="/etc/profile"
RSYSLOG_CNF="/etc/rsyslog.conf"
JOURNALD_CFG="/etc/systemd/journald.conf"
PASSWD="/etc/passwd"
GROUP="/etc/group"
SHADOW="/etc/shadow"
GSHADOW="/etc/gshadow"

# Other constants
OWNER_GROUP="root:root"
